war/war/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'cards.views.home', name='home'),
    url(r'^filters/$', 'cards.views.filters', name='filters'),
    url(r'^tags/$', 'cards.views.template_tags', name='tags'),
    url(r'^first/filter/$', 'cards.views.first_filter', name='tags'),
    url(r'^suit/filter/$', 'cards.views.suit_filter', name='suits'),
    url(r'^profile/$', 'cards.views.profile', name='profile'),
    url(r'^get_card/$', 'cards.views.get_card', name='get_card'),
    url(r'^faq/$', 'cards.views.faq', name='faq'),
    url(r'^blackjack/$', 'cards.views.blackjack', name='blackjack'),
    url(r'^poker/$', 'cards.views.poker', name='poker'),
    url(r'^war/$', 'cards.views.war', name='war'),
    url(r'^interactive/$', 'cards.views.interactive', name='interactive'),



    url(r'^register/$', 'cards.views.register', name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

war/cards/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Card(models.Model):
    SPADE = 0
    CLUB = 1
    DIAMOND = 2
    HEART = 3
    SUITS = (
        (SPADE, "spade"),
        (CLUB, "club"),
        (DIAMOND, "diamond"),
        (HEART, "heart")
    )
    suit = models.PositiveSmallIntegerField(choices=SUITS)
    rank = models.CharField(max_length=5)
    image = models.ImageField(upload_to='card_images', blank=True, null=True)

    def get_ranking(self):
        rankings = {
            'two': 2,
            'three': 3,
            'four': 4,
            'five': 5,
            'six': 6,
            'seven': 7,
            'eight': 8,
            'nine': 9,
            'ten': 10,
            'jack': 11,
            'queen': 12,
            'king': 13,
            'ace': 14
        }
        return rankings[self.rank]

    def get_war_result(self, card_to_check):
        my_ranking = self.get_ranking()
        card_to_check_ranking = card_to_check.get_ranking()

        print my_ranking, card_to_check_ranking

        if my_ranking > card_to_check_ranking:
            return 1
        elif my_ranking == card_to_check_ranking:
            return 0
        else:
            return -1

    def __unicode__(self):
        return u"{} of {}s".format(self.rank, self.get_suit_display())



class Player(AbstractUser):
    phone = models.CharField(max_length=12, help_text="Format should be: 650-111-2222")

    def get_wins(self):
        return WarGame.objects.filter(player=self, result=WarGame.WIN).count()

    def get_losses(self):
        return WarGame.objects.filter(player=self, result=WarGame.LOSS).count()

    def get_ties(self):
        return WarGame.objects.filter(player=self, result=WarGame.TIE).count()

    def get_record_display(self):
        return "{}-{}-{}".format(self.get_wins(), self.get_losses(), self.get_ties())


class WarGame(models.Model):
    LOSS = -1
    TIE = 0
    WIN = 1
    RESULTS = (
        (LOSS, "loss"),
        (TIE, "tie"),
        (WIN, "win")
    )

    result = models.IntegerField(choices=RESULTS)
    player = models.ForeignKey(Player)

war/cards/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from models import Player
from django.core.mail import EmailMultiAlternatives









class EmailUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Player
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(EmailUserCreationForm, self).save(commit=commit)
        text_content = 'Thank you for signing up for our website, {}'.format(user.username)
        html_content = '<h2>Thanks {} for signing up!</h2> <div>I hope you enjoy using our ' \
                       'site</div>'.format(user.username)
        msg = EmailMultiAlternatives("Welcome!", text_content, settings.DEFAULT_FROM_EMAIL, [user.email])
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return user

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            Player.objects.get(username=username)
        except Player.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

war/cards/views.py
import json
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render, redirect
from forms import EmailUserCreationForm
from models import Card, WarGame
from utils import get_random_comic, create_deck


def home(request):
    data = {
        'cards': Card.objects.all(),
        'comic' : get_random_comic()
    }

    return render(request, 'home.html', data)


def filters(request):
    data = {
        'cards': Card.objects.all()
    }

    return render(request, 'card_filters.html', data)

def interactive(request):
    return render(request, 'interactive.html')

def get_card(request):
    cards = list(Card.objects.order_by('?'))
    user_card = cards[0]
    print user_card
    dealer_card = cards[1]
    print dealer_card
    card = { "user_card" : user_card.rank,
              "dealer_card" : dealer_card.rank }
    data = json.dumps(card)
    return HttpResponse(data, content_type='application/json')

# you still have to write the evaluation and storing of wins/loss'
def result(request):
    pass


def template_tags(request):
    data = {
        'cards': Card.objects.all()
    }

    return render(request, 'card_template_tags.html', data)


def first_filter(request):
    data = {
        'cards': Card.objects.all()
    }

    return render(request, 'first_filter.html', data)


def suit_filter(request):
    data = {
        'cards': Card.objects.all()
    }

    return render(request, 'card_suits.html', data)


@login_required
def profile(request):
    return render(request, 'profile.html', {
        'games': WarGame.objects.filter(player=request.user),
        'wins': request.user.get_wins(),
        'losses': request.user.get_losses()
    })


def faq(request):
    return render(request, 'faq.html', {})


def blackjack(request):
    data = {
        'cards': Card.objects.order_by('?')[:2]
    }

    return render(request, 'blackjack.html', data)


def poker(request):
    data = {
        'cards': Card.objects.order_by('?')[:5]
    }

    return render(request, 'poker.html', data)


def register(request):
    if request.method == 'POST':
        form = EmailUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("profile")
    else:
        form = EmailUserCreationForm()

    return render(request, "registration/register.html", {
        'form': form,
    })


@login_required()
def war(request):
    cards = list(Card.objects.order_by('?'))
    user_card = cards[0]
    dealer_card = cards[1]

    result = user_card.get_war_result(dealer_card)
    WarGame.objects.create(result=result, player=request.user)

    return render(request, 'war.html', {
        'user_cards': [user_card],
        'dealer_cards': [dealer_card],
        'result': result
    })

war/cards/templates/base_template.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="{% static "js/cards.js" %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static "css/cards.css" %}">
    </head>
    <body>
        <div>
            <img id="joker" width="40px" src="{% static "img/red_joker.jpg" %}">
            <a href="{% url "profile" %}">Profile</a> |  <a href="{% url "faq" %}">FAQ</a> | <a href="{% url "war" %}">War</a>

            <span style="float:right;">
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a> | <a href="{% url 'register' %}">Register</a>
                {% endif %}
            </span>
        </div>
        <h1>Welcome to our Card Game!</h1>
        {% block content %}{% endblock content %}
    </body>
</html>

war/cards/templates/blackjack.html
{% extends 'base_template.html' %}

{% block content %}
    <h2>Blackjack!</h2>
    <p>Here's your hand...</p>
    {% include 'includes/hand2.html' %}
{% endblock content %}

war/cards/templates/card_filters.html
We have {{ cards | length }} cards!

{% for card in cards %}
    <div>
        <p>
            Capitalized Suit: {{ card.suit | capfirst }} <br>
            Uppercased Rank: {{ card.rank | upper }}
        </p>
    </div>
{% endfor %}

war/cards/templates/card_suits.html
{% load list_filters %}

{% for card in cards|suit:"diamond"  %}
    <p>Suit: {{ card.get_suit_display }}, Rank: {{ card.rank }}</p>
{% endfor %}

war/cards/templates/card_template_tags.html
<style>
    .odd {
        color: blue;
    }
</style>


It's {% now "SHORT_DATETIME_FORMAT" %}!

{% for card in cards %}
    <p class="{% cycle 'even' 'odd' %}">
        Suit: {{ card.get_suit_display }}, Rank: {{ card.rank }}
    </p>
{% endfor %}

war/cards/templates/cards.html
{% extends "base_template.html" %}

{% block content %}
{% for card in cards %}
    <p>Suit: {{ card.get_suit_display }}, Rank: {{ card.rank }}</p>

{% endfor %}

{% endblock %}

war/cards/templates/faq.html
{% extends 'base_template.html' %}

{% block content %}
    <p>Q: Can I win real money on this website?</p>
    <p>A: Nope, this is not real, sorry.</p>
{% endblock content %}

war/cards/templates/first_filter.html
{% load list_filters %}

{{ cards|first }}

{% with cards|first as first_card %}
    <p>Suit: {{ first_card.get_suit_display }}, Rank: {{ first_card.rank }}</p>
{% endwith %}

war/cards/templates/home.html
{% extends "base_template.html" %}

{% block content %}

    <h2>Some Random Inspiration</h2>
    <div>
        <h3>{{ comic.safe_title }} - {{ comic.year }}</h3>
        <img alt="{{ comic.alt }}" src="{{ comic.img }}">
        <p>{{ comic.transcript }}</p>
    </div>
{% endblock %}

war/cards/templates/includes/hand.html
{% for card in cards %}
    <p>Suit: {{ card.get_suit_display }}, Rank: {{ card.rank }}</p>
{% endfor %}

war/cards/templates/includes/hand2.html
{% for card in cards %}
    <img width="100px" src="{{ card.image.url }}">
{% endfor %}

war/cards/templates/interactive.html
{% extends "base_template.html" %}

{% block content %}

    <button id="get_card">Get card</button>
    <div id="player"></div>
{% endblock %}

war/cards/templates/poker.html
{% extends 'base_template.html' %}

{% block content %}
    <h2>Poker!</h2>
    <p>Here's your hand...</p>
    {% include 'includes/hand2.html' %}
{% endblock content %}

war/cards/templates/profile.html
{% extends 'base_template.html' %}

{% block content %}
    <p>Hi {{ user.username }}, you have 0 wins and 0 loses.</p>
    <p>Your email address is {{ user.email }}</p>

    <h2>Past Games</h2>
    {% for game in games %}
        <p>{{ game.get_result_display }}</p>
        <p>Hi {{ user.username }}, you have {{ wins }} wins and {{ losses }} loses.</p>

    {% endfor %}
{% endblock content %}

war/cards/templates/war.html
{% extends 'base_template.html' %}

{% block content %}
    <h2>War!</h2>

    <div style="float:left; margin-right: 50px;">
        <h3>Player's Card</h3>
        {% include 'includes/hand2.html' with cards=user_cards %}
    </div>

    <div style="float: left;">
        <h3>Dealer's Card</h3>
        {% include 'includes/hand2.html' with cards=dealer_cards %}
    </div>

    <div style="clear:both;"></div>

    <div style="margin-top:30px;">
        {% if result == 1 %}
            <h2>You won!</h2>
        {% elif result == 0 %}
            <h2>You tied.</h2>
        {% else %}
            <h2>You lost...</h2>
        {% endif %}
    </div>


{% endblock content %}